services:
  lancer-lite-vtt:
    build:
      dockerfile: ./Dockerfile
    ports: 
      # - local-port:container-port
      # - Foundry default port is 30000.
      - 3000:30000
    volumes:
      # Dockerfile sets Foundry data directory to /app/data
      - ./lancer-lite:/app/data/Data/systems/lancer-lite/